version: '3'
services:
  prod_web:
    container_name: prod_instapy
    command: python docker_quickstart_server.py
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - prod_selenium
    volumes:
      - ./logs:/code/logs
    external_links:
      - mongodb
    networks:
      - default
      - mongo_default
  prod_selenium:
    container_name: prod_selenium
    image: selenium/standalone-chrome
    shm_size: 128M

networks:
  mongo_default:
    external: true
