version: '3'
services:
  d_web:
    container_name: dev_instagrambot
    build:
      context: .
      dockerfile: ./docker_conf/dev_python/Dockerfile
    volumes:
      - .:/code
    ports:
      - '22:22'
    depends_on:
      - d_selenium
    links:
      - d_selenium:selenium
    external_links:
      - mongodb
    networks:
      - default
      - mongo_default
    environment:
      - PYTHONPATH=/code
  d_selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - '5901:5900'
    shm_size: 512M

networks:
  mongo_default:
    external: true
