version: '3'
services:
  web:
    # container_name: instagrambot
    command:
      [
        './wait-for-selenium.sh',
        'http://selenium:4444/wd/hub',
        '--',
        'python',
        'docker_quickstart.py',
      ]
    environment:
      - PYTHONUNBUFFERED=0
      - TZ=Europe/Rome
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - selenium
    volumes:
      - ./logs:/code/logs
    external_links:
      - mongodb
    networks:
      - default
      - mongo_default
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - '5900:5900'
    shm_size: 128M

networks:
  mongo_default:
    external: true
