version: '3'
services:
  # redis:
  #   container_name: redis
  #   restart: always
  #   volumes:
  #     - ./redis/data:/data
  #   image: redis:3.2-alpine
  #   ports:
  #     - '6379:6379'
  # mongodb:
  #   container_name: mongodb
  #   restart: always
  #   volumes:
  #     - ./mongodb/configdb:/data/configdb
  #     - ./mongodb/db:/data/db
  #   image: mongo:3.6.6
  #   ports:
  #     - '27017:27017'
  bot:
    container_name: prod_instapy
    restart: always
    command: python docker_quickstart.py
    environment:
      - PYTHONUNBUFFERED=0
      - PRODUCTION=True
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - prod_selenium
    volumes:
      - ./logs:/code/logs
    networks:
      - default
      - mongodb_default
    external_links:
      - mongodb
  prod_selenium:
    container_name: prod_selenium
    restart: always
    image: selenium/standalone-chrome
    shm_size: 512M

networks:
  mongodb_default:
    external: true
