version: '3'
services:
  redis:
    container_name: redis
    restart: always
    volumes:
      - ./data:/data
    image: redis:3.2-alpine
    ports:
      - '6379:6379'
  mongodb:
    container_name: mongodb
    restart: always
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    image: mongo:3.6.6
    ports:
      - '27017:27017'
  bot:
    container_name: prod_instapy
    restart: always
    command: python docker_quickstart_server.py
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/python/Dockerfile
    depends_on:
      - prod_selenium
      - mongodb
    volumes:
      - ./logs:/code/logs
  prod_selenium:
    container_name: prod_selenium
    restart: always
    image: selenium/standalone-chrome
    shm_size: 512M
